# Handwritten Digit Classification Using SVD

### Form a matrix A for each digit, such that each row in A represents an image of that digit. (You will have 10 A's)

In [3]:
# Import numpy and pandas
import numpy as np
import pandas as pd

In [4]:
# read the trainInput.csv file
df_trainInput = pd.read_csv('svd_train/trainInput.csv', header=None)
df_trainInput

0      1      2     3      4     5      6     7      8     9     ...  \
0   -1.000 -1.000 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
1   -1.000 -1.000 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
2   -1.000 -1.000 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
3   -1.000 -0.813 -1.000  -1.0 -1.000  -1.0 -0.830  -1.0 -1.000  -1.0  ...   
4   -1.000 -0.671 -1.000  -1.0 -1.000  -1.0  0.442  -1.0 -1.000  -1.0  ...   
..     ...    ...    ...   ...    ...   ...    ...   ...    ...   ...  ...   
251 -0.991  0.126 -0.179  -1.0  0.439  -1.0 -1.000  -1.0 -0.811  -1.0  ...   
252 -1.000 -0.095 -1.000  -1.0 -0.199  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
253 -1.000 -0.671 -1.000  -1.0 -0.883  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
254 -1.000 -0.828 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0  ...   
255 -1.000 -1.000 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  -1.0  ...   

      1697   1698   1699  1700  1701   1702  1703   1704  1705   1706  
0   -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
1   -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
2   -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
3   -1.000 -0.567 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
4   -0.986 -0.064 -1.000  -1.0  -1.0 -1.000  -1.0 -0.948  -1.0 -0.338  
..     ...    ...    ...   ...   ...    ...   ...    ...   ...    ...  
251 -1.000 -1.000 -0.633  -1.0  -1.0 -0.974  -1.0 -1.000  -1.0 -1.000  
252 -1.000 -1.000 -0.782  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
253 -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
254 -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  
255 -1.000 -1.000 -1.000  -1.0  -1.0 -1.000  -1.0 -1.000  -1.0 -1.000  

[256 rows x 1707 columns]

In [5]:
# transpose trainInput
train_input_T = df_trainInput.T
train_input_T

0    1    2      3      4      5      6      7      8      9    ...  \
0    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.631  0.862 -0.167  ...   
1    -1.0 -1.0 -1.0 -0.813 -0.671 -0.809 -0.887 -0.671 -0.853 -1.000  ...   
2    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -0.996  ...   
3    -1.0 -1.0 -1.0 -1.000 -1.000 -0.273  0.684  0.960  0.450 -0.067  ...   
4    -1.0 -1.0 -1.0 -1.000 -1.000 -0.928 -0.204  0.751  0.466  0.234  ...   
...   ...  ...  ...    ...    ...    ...    ...    ...    ...    ...  ...   
1702 -1.0 -1.0 -1.0 -1.000 -1.000 -0.889  0.497  0.988  0.244 -0.861  ...   
1703 -1.0 -1.0 -1.0 -1.000 -1.000 -0.961 -0.211  0.647  0.464 -0.071  ...   
1704 -1.0 -1.0 -1.0 -1.000 -0.948 -0.307 -0.718 -0.178  0.543  1.000  ...   
1705 -1.0 -1.0 -1.0 -1.000 -1.000 -0.806  0.417  1.000  0.627 -0.559  ...   
1706 -1.0 -1.0 -1.0 -1.000 -0.338  0.637  1.000  0.464  0.428 -0.161  ...   

        246    247    248    249    250    251    252    253    254  255  
0     0.304  0.823  1.000  0.482 -0.474 -0.991 -1.000 -1.000 -1.000 -1.0  
1    -0.671 -0.671 -0.033  0.761  0.762  0.126 -0.095 -0.671 -0.828 -1.0  
2    -1.000 -1.000 -1.000 -0.109  1.000 -0.179 -1.000 -1.000 -1.000 -1.0  
3    -0.318  1.000  0.536 -0.987 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  
4     0.466  0.639  1.000  1.000  0.791  0.439 -0.199 -0.883 -1.000 -1.0  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  ...  
1702  0.401  0.752  1.000  0.609  0.206 -0.974 -1.000 -1.000 -1.000 -1.0  
1703 -0.983  0.635  0.236 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  
1704 -0.822  0.720 -0.716 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  
1705  0.491  0.866 -0.712 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  
1706 -0.682  0.195  0.755  0.415 -0.541 -1.000 -1.000 -1.000 -1.000 -1.0  

[1707 rows x 256 columns]

In [6]:
# read the trainOutput.csv file
df_trainOut = pd.read_csv('svd_train/trainOutput.csv', header=None)
df_trainOut

0     1     2     3     4     5     6     7     8     9     ...  1697  \
0     6     5     4     7     3     6     3     1     0     1  ...     8   

   1698  1699  1700  1701  1702  1703  1704  1705  1706  
0     0     5     1     9     8     9     7     9     8  

[1 rows x 1707 columns]

In [7]:
# Convert trainOutput.csv file into an array
trainOut_array = df_trainOut.iloc[0]
trainOut_array

0       6
1       5
2       4
3       7
4       3
       ..
1702    8
1703    9
1704    7
1705    9
1706    8
Name: 0, Length: 1707, dtype: int64

In [8]:
# Make matrix A a dictionary to store 10 digits from 0-9
A = {1:[], 2:[], 3:[], 4:[], 5:[],
    6:[], 7:[], 8:[], 9:[], 0:[]}

# Make a for loop assign each row in trainInput to a digit in matrix A
for i in range(len(trainOut_array)):
    A[trainOut_array[i]].append(train_input_T.iloc[i])

# Convert each matrix A into a np.array to access the shape of the matrix more easily
# and print out the shape of each matrix A
for k in A.keys():
    A[k] = np.array(A[k])
    print(f'Digit {k}\'s matrix A shape: {A[k].shape}')

Digit 1's matrix A shape: (252, 256)
Digit 2's matrix A shape: (202, 256)
Digit 3's matrix A shape: (131, 256)
Digit 4's matrix A shape: (122, 256)
Digit 5's matrix A shape: (88, 256)
Digit 6's matrix A shape: (151, 256)
Digit 7's matrix A shape: (166, 256)
Digit 8's matrix A shape: (144, 256)
Digit 9's matrix A shape: (132, 256)
Digit 0's matrix A shape: (319, 256)


In [9]:
# Printing out the numbers of rows for each matrix A 
# and check the total number of rows match the number of training digits
final = 0

print('Number of rows in each matrix A:')
for m in A.keys():
    print(f'    Digit {m}\'s matrix A rows: {len(A[m])}')
    final += len(A[m])
print(f'The total amount of rows across all matrices A is {final}')

Number of rows in each matrix A:
    Digit 1's matrix A rows: 252
    Digit 2's matrix A rows: 202
    Digit 3's matrix A rows: 131
    Digit 4's matrix A rows: 122
    Digit 5's matrix A rows: 88
    Digit 6's matrix A rows: 151
    Digit 7's matrix A rows: 166
    Digit 8's matrix A rows: 144
    Digit 9's matrix A rows: 132
    Digit 0's matrix A rows: 319
The total amount of rows across all matrices A is 1707


Since there are a total of 1707 training digits and the total number of rows across all matrices A is 1707, we can conclude that all rows are correctly assigned to their respective matrices.

### Determine the singular value decomposition for each A. (Right singular vectors V, are an orthogonal basis in the image space of that digit. We will refer to the right singular vectors as "singular images.") You should get 10 sets of singular images, one for each digit.

In [12]:
# Create a dictionary that stores 10 sets of singular digits

s_images = {}

# Use svd from np.linalg to get the right singular vectors for each digit
for d in A.keys():
    # Print out each matrix A shape to compare to SVD shapes later
    print(f'Digit {d}\'s matrix A shape: {A[d].shape}')
    u, s, vt = np.linalg.svd(A[d])
    # Print out the shape of left singular vectors (u), singular values (s),
    # and right singular vectors (vt)
    print(f'Digit {d}\'s singular value decomposition:')
    print(f'    Left singular vectors shape: {u.shape}')
    print(f'    Singular values length: {s.shape}')
    print(f'    Singular images (right singular vectors) shape: {vt.shape}')
    print()
    # Store each right singular vector to their respective digits
    s_images[d] = vt

Digit 1's matrix A shape: (252, 256)
Digit 1's singular value decomposition:
    Left singular vectors shape: (252, 252)
    Singular values length: (252,)
    Singular images (right singular vectors) shape: (256, 256)

Digit 2's matrix A shape: (202, 256)
Digit 2's singular value decomposition:
    Left singular vectors shape: (202, 202)
    Singular values length: (202,)
    Singular images (right singular vectors) shape: (256, 256)

Digit 3's matrix A shape: (131, 256)
Digit 3's singular value decomposition:
    Left singular vectors shape: (131, 131)
    Singular values length: (131,)
    Singular images (right singular vectors) shape: (256, 256)

Digit 4's matrix A shape: (122, 256)
Digit 4's singular value decomposition:
    Left singular vectors shape: (122, 122)
    Singular values length: (122,)
    Singular images (right singular vectors) shape: (256, 256)

Digit 5's matrix A shape: (88, 256)
Digit 5's singular value decomposition:
    Left singular vectors shape: (88, 88)
  

Each matrix A has a shape of m x 256, where m is the number of rows (images) and 256 is the number of columns (pixel values). The singular images (right singular vectors) have a shape of 256 x 256, therefore, they have an orthogonal basis at the column space matrix A. We can conclude that the singular value decomposition has been correctly applied.

### Express test images as a linear combination of the first k=20 singular images of each digit. (This is a least square problem of the form Ax = b).

In [15]:
# Read the testInput.csv file
df_testInput = pd.read_csv('svd_train/testInput.csv', header=None)
df_testInput

0     1      2     3      4      5     6      7     8     9     ...  \
0    -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
1    -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
2    -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
3    -1.0  -1.0 -0.593  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
4    -1.0  -1.0  0.700  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
..    ...   ...    ...   ...    ...    ...   ...    ...   ...   ...  ...   
251  -1.0  -1.0 -1.000  -1.0 -0.867 -0.641  -1.0 -0.308  -1.0  -1.0  ...   
252  -1.0  -1.0 -1.000  -1.0 -1.000 -0.812  -1.0 -1.000  -1.0  -1.0  ...   
253  -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
254  -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   
255  -1.0  -1.0 -1.000  -1.0 -1.000 -1.000  -1.0 -1.000  -1.0  -1.0  ...   

      1997   1998   1999  2000  2001  2002  2003   2004   2005  2006  
0   -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
1   -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
2   -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
3   -1.000 -0.885 -0.980  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
4   -0.766 -0.280  0.078  -1.0  -1.0  -1.0  -1.0 -0.031 -0.534  -1.0  
..     ...    ...    ...   ...   ...   ...   ...    ...    ...   ...  
251 -1.000 -0.400 -0.978  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
252 -1.000 -0.998 -0.109  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
253 -1.000 -1.000  0.360  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
254 -1.000 -1.000 -0.381  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  
255 -1.000 -1.000 -1.000  -1.0  -1.0  -1.0  -1.0 -1.000 -1.000  -1.0  

[256 rows x 2007 columns]

In [16]:
# Transpose testInput
testInput_T = df_testInput.T
testInput_T

0    1    2      3      4      5      6      7      8      9    ...  \
0    -1.0 -1.0 -1.0 -1.000 -1.000 -0.948 -0.561  0.148  0.384  0.904  ...   
1    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000  ...   
2    -1.0 -1.0 -1.0 -0.593  0.700  1.000  1.000  1.000  1.000  0.853  ...   
3    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000  ...   
4    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.858 -0.106  0.802  ...   
...   ...  ...  ...    ...    ...    ...    ...    ...    ...    ...  ...   
2002 -1.0 -1.0 -1.0 -1.000 -1.000 -0.417  0.814  1.000  0.775 -0.723  ...   
2003 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -0.855  0.209  0.941  0.809  ...   
2004 -1.0 -1.0 -1.0 -1.000 -0.031  0.752 -0.431 -1.000 -1.000 -1.000  ...   
2005 -1.0 -1.0 -1.0 -1.000 -0.534  0.578  1.000  0.301 -0.328 -0.939  ...   
2006 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000  0.399  0.949 -0.399  ...   

        246    247    248    249    250    251  252  253  254  255  
0    -1.000 -0.908  0.430  0.622 -0.973 -1.000 -1.0 -1.0 -1.0 -1.0  
1    -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0 -1.0 -1.0 -1.0  
2     1.000  0.717  0.333  0.162 -0.393 -1.000 -1.0 -1.0 -1.0 -1.0  
3    -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0 -1.0 -1.0 -1.0  
4     0.901  0.901  0.901  0.290 -0.369 -0.867 -1.0 -1.0 -1.0 -1.0  
...     ...    ...    ...    ...    ...    ...  ...  ...  ...  ...  
2002  1.000  1.000  0.554  0.184 -0.484 -1.000 -1.0 -1.0 -1.0 -1.0  
2003 -1.000  0.319  1.000  0.056 -1.000 -1.000 -1.0 -1.0 -1.0 -1.0  
2004  1.000  0.928 -0.393 -1.000 -1.000 -1.000 -1.0 -1.0 -1.0 -1.0  
2005  1.000  0.430  0.200 -0.061 -0.975 -1.000 -1.0 -1.0 -1.0 -1.0  
2006 -1.000 -0.505  0.907  0.655 -0.950 -1.000 -1.0 -1.0 -1.0 -1.0  

[2007 rows x 256 columns]

In [17]:
# We need to express each test image as a linear combination by finding the coefficients (x)
# convert testInput_T into a np.array for easier access
test_image_array= np.array(testInput_T)

# Create a list that holds a dictionary of coefficients from digits 0-9 for each test image
x_list = []

# Loop through each test image
for row in range(len(test_image_array)):
    test_image = test_image_array[row]
    # Create a dictionary to store coefficients that would be appended later to x_list
    x_coef = {}
    # Loop through each digit to find the coefficient for each digit
    for d in s_images.keys():
        v_A = s_images[d][0:20].T
        x = np.linalg.pinv(v_A)@test_image
        x_coef[d] = x
    x_list.append(x_coef)
# Print out the first five elements of x_list
print(x_list[0:5])

[{1: array([ 7.18350384, -0.05136589,  1.49083109,  0.98947995, -0.1653551 ,
        4.13234743, -0.95732688,  0.7623245 , -1.55905772,  3.34351012,
       -0.45985687,  1.04857239, -0.5388918 , -0.7610206 , -0.44893412,
       -0.64506411, -0.4519482 , -1.40257684,  1.15601582,  0.37393031]), 2: array([ 7.19285783, -0.58763115,  0.48685216,  2.07888026, -3.72047026,
       -3.84501636,  0.89360075,  1.82388366, -1.9582215 , -0.63464952,
       -2.42213996,  1.16167719, -1.04270674,  0.36627084, -1.17241428,
       -0.34896153,  3.76007856,  0.60774207,  0.86264051, -1.33529276]), 3: array([ 7.808613  , -0.41321026, -2.88700221, -5.42480417,  3.38578424,
       -1.56627691,  1.58393959,  0.0079002 ,  0.60269025, -0.53767832,
       -1.63794034, -3.88882098,  0.86534402,  0.42814356, -0.85373993,
        0.34661926, -0.29864161, -0.83019957, -0.41657096, -0.32304571]), 4: array([10.97597174, -1.61215334, -2.45639824,  2.95559072, -0.79141932,
       -0.2312318 ,  2.79816968, -2.56811049

### Compute the distance between test images and their least square approximations.

In [19]:
# We need to find the least square approximation before we can compute the distance
# Create a list that holds the distance between test images and their least square approximations
distance_list = []

for row in range(len(test_image_array)):
    test_image = test_image_array[row]
    # Create a dictionary to store the distance
    distances_dict = {}
    for d in s_images.keys():
        v_A = s_images[d][0:20].T
        x = x_list[row][d]
        # Compute the least-square approximation with linear combination
        ls_approx = v_A @ x
        # Compute the distance between test images and ls_approx (||testImage - v_Ax||)
        distance = np.linalg.norm(test_image - ls_approx)
        distances_dict[d] = distance
    distance_list.append(distances_dict)
# Print out the first five elements of distance_list
print(distance_list[0:5])

[{1: 10.89540752782552, 2: 9.569496016713451, 3: 8.69160717469732, 4: 7.284899373349757, 5: 9.337940471185119, 6: 9.545622395603948, 7: 7.114044277771491, 8: 8.23631827035213, 9: 3.401388165728014, 0: 9.450711113293487}, {1: 11.49661405255736, 2: 9.112643048644012, 3: 10.416279918277695, 4: 9.436813981198457, 5: 10.2326200384847, 6: 5.51482226415027, 7: 11.448301743726176, 8: 10.653983827469792, 9: 10.843435487864374, 0: 7.987032051625504}, {1: 12.148701369433459, 2: 8.665643110508773, 3: 4.16866221588947, 4: 11.73659611985253, 5: 9.105363881895078, 6: 10.195265866043147, 7: 9.879519746112287, 8: 7.7730444184327, 9: 9.382345183715481, 0: 8.947268657206102}, {1: 11.188172189639028, 2: 9.514208787131174, 3: 9.945517015753158, 4: 9.44687230797111, 5: 10.272117616753732, 6: 7.928856785267235, 7: 11.312533079159639, 8: 10.776753776033, 9: 11.05127658673383, 0: 7.747874613285437}, {1: 11.414211664632992, 2: 9.804297471853179, 3: 11.469534914258691, 4: 10.496134354933375, 5: 11.17464396338568

### Classify each test image to be the digit corresponding to the smallest residual

In [21]:
# We classify each unknown imaget to be the digit corresponding to the smallest error
# i.e. min||testImage - v_Ax||
# Create a list to store the digit corresponding to the smallest residual
digit_list = []
# Create a loop to check each distance in distance list for the smallest residual
for i in distance_list:
    temp_list = []
    for d in i.keys():
        temp_list.append(i[d])
    # Use the min function to find the smallest residual in the list
    min_digit = min(temp_list)
    # Finds the digit corresponding to the residual
    for c in i.keys():
        if min_digit == i[c]:
            digit_list.append(c)
            break;
# Print the list of predicted digits
print('List of predicted digits: ')
print(digit_list)
print(f'Predicted digit list length: {len(digit_list)}')

List of predicted digits: 
[9, 6, 3, 0, 6, 0, 0, 0, 6, 9, 6, 2, 3, 4, 0, 3, 1, 6, 9, 6, 2, 2, 4, 9, 6, 2, 0, 5, 8, 3, 7, 0, 0, 0, 7, 9, 8, 0, 0, 7, 0, 8, 1, 0, 7, 1, 0, 4, 2, 0, 8, 5, 1, 2, 0, 6, 5, 9, 2, 0, 9, 0, 4, 2, 0, 9, 1, 2, 2, 1, 8, 3, 7, 2, 0, 9, 0, 1, 2, 1, 2, 0, 7, 2, 0, 6, 7, 3, 2, 0, 9, 0, 4, 8, 2, 0, 7, 0, 0, 9, 0, 6, 7, 3, 0, 7, 2, 8, 9, 4, 3, 3, 9, 9, 7, 0, 5, 9, 9, 6, 8, 5, 7, 0, 6, 8, 5, 6, 1, 4, 8, 5, 0, 1, 4, 7, 0, 0, 7, 7, 9, 6, 6, 3, 3, 0, 7, 5, 0, 9, 6, 2, 2, 4, 8, 9, 1, 0, 1, 0, 0, 9, 0, 6, 9, 2, 9, 0, 3, 3, 4, 0, 9, 0, 4, 0, 8, 5, 0, 4, 1, 0, 6, 0, 4, 0, 6, 4, 1, 4, 1, 0, 1, 0, 4, 5, 7, 2, 0, 6, 3, 1, 8, 0, 5, 0, 1, 8, 0, 0, 1, 3, 8, 0, 2, 0, 6, 8, 0, 9, 0, 9, 8, 0, 3, 2, 1, 8, 0, 3, 2, 2, 4, 6, 2, 9, 6, 4, 1, 5, 2, 5, 5, 1, 6, 4, 5, 8, 1, 0, 1, 8, 4, 7, 8, 4, 6, 0, 4, 8, 4, 7, 7, 0, 8, 4, 0, 9, 2, 8, 4, 6, 0, 1, 2, 3, 6, 6, 6, 0, 3, 3, 0, 6, 6, 8, 2, 0, 1, 7, 9, 9, 7, 3, 7, 9, 9, 6, 6, 7, 7, 9, 7, 9, 9, 7, 5, 6, 8, 2, 7, 5, 6, 8, 1, 0, 1, 1, 1, 6, 7, 6, 8, 5, 

### Calculate the overall correct classification rate, as well as correct classification rate for each digit in a confusion matrix.

In [23]:
# Load testOutput.csv
df_testOut = pd.read_csv('svd_train/testOutput.csv', header=None)
df_testOut

0     1     2     3     4     5     6     7     8     9     ...  1997  \
0     9     6     3     6     6     0     0     0     6     9  ...     7   

   1998  1999  2000  2001  2002  2003  2004  2005  2006  
0     5     2     0     4     3     9     4     0     1  

[1 rows x 2007 columns]

In [24]:
# Overall classification rate = (Number of Correct Predictions/Total Number of Test Images) x 100
correct_pred = 0
testOut_list = df_testOut.iloc[0]
# Create a loop that checks how many digits from the testOutput list match our predicted list
for i in range(len(testOut_list)):
    if (testOut_list[i] == digit_list[i]):
        correct_pred += 1
# Use the formula above and print out the overall classification rate and correct predictions
print(f'Number of Correct Predictions: {correct_pred}')
class_rate = (correct_pred/len(testOut_list)) * 100
print(f'Overall correct classification rate: {class_rate}')

Number of Correct Predictions: 1886
Overall correct classification rate: 93.97110114598904


In [25]:
# Import metrics from sklearn to access confusion matrix
from sklearn import metrics

confusion_m = metrics.confusion_matrix(testOut_list, digit_list)
# Print out the confusion matrix. Row (true labels) is read from top to bottom as 0-9 respectively
# and column (predicted labels) is read from left to right as 0-9 respectively
# The correct classification is along the diagonal for each digit 0-9 respectively
print('Confusion Matrix:')
print('Rows: True Labels (0-9) Columns: Predicted Labels (0-9)')
print(confusion_m)

Confusion Matrix:
Rows: True Labels (0-9) Columns: Predicted Labels (0-9)
[[355   0   2   0   1   0   0   0   0   1]
 [  0 259   0   0   3   0   2   0   0   0]
 [  8   1 179   2   3   0   0   1   4   0]
 [  1   0   4 148   1   8   0   1   2   1]
 [  1   1   0   0 187   1   1   3   0   6]
 [  8   1   2   4   0 140   0   0   2   3]
 [  2   0   0   0   2   2 164   0   0   0]
 [  0   1   1   0   3   0   0 139   0   3]
 [  4   0   2   6   0   1   0   0 149   4]
 [  0   1   0   1   4   0   0   4   1 166]]
